### PR TITLE
Refs #158 - don't hide selected columns

### LINKED ISSUE #158: Don't replace selected columns with "..."
These 2 queries produce the same result:

```python
list(Author.objects.all())
list(Author.objects.only('pk'))
```
result:
```
- db: SELECT ... FROM "testapp_author"
- db: SELECT ... FROM "testapp_author"
```

It will be helpfull to not hide selected columns, because without reading the code in parallel we don't know how many fields are concerned by the query.

I will propose a PR.

### PR DESCRIPTION
**Pull request by zebuline**
Fixes #158

If this change is accepted, it can be really usefull for our DBAs, who are reviewing our pull requests which contain updates on perf rec files :)

### CODE REVIEW

**Comment by adamchainz** [comment]
Hi

The reason the selected columns are collapsed is because they change frequently in applications when migrations add/remove columns. Also most DB's that Django natively supports are row-based in their default configurations, so there is not much of a performance penalty for selecting extra columns, except from certain cases such as one column being quite large and thus consuming extra network bandwidth. Have your DBA's given any reasoning behind wanting to see them?

I also think this change isn't great for 99% of users, who probably don't have humans inspecting the column list and appreciate the lower churn and more compact output when columns are added/removed from tables. So it would have to be a default-off option at least if were to add it.

**Comment by zebuline** [comment]
Hi, thank you for your feedback.

You're right, I will add a default-off option for this. I thought about it last week, and I forgot ... :)

> Have your DBA's given any reasoning behind wanting to see them?
I asked to one of my colleague to answer. He should respond soon.

**Comment by zebuline** [comment]
Yes, no problem. I planed to extend the defaults:
```python
    defaults = {
        'MODE': 'once',
        'HIDE_COLUMNS': True,
    }
```
(`hide_columns True` or `show_columns False` ? What do you prefer ?)

**Comment by adamchainz** [comment]
Oh, I guess `HIDE_COLUMNS` defaulting to `True` makes sense?

**Comment by zebuline** [comment]
Ok for me, thanks :)

**Comment by marco44** [comment]
Hi, I'm the requested DBA :)

I'll only speak about PostgreSQL and Oracle, to be sure I don't say anything I'm not sure of, but what follows is probably valid also at least with SQL Server and DB2. And focus on some very obvious queries for the sake of example, but there are many more complicated occurrences where having the columns will help me. The examples will be with PostgreSQL, but Oracle is very similar for these cases.

There are many reasons why the columns returned are important, but here are the firsts that come to my mind:

* If all the requested columns are in an index, there is no need to go check the table (that's called an index only scan). For instance, this query changes completely:

```
create table test (a int, b varchar, c varchar);
insert into test select (random()*1000000)::int,i::text, repeat (i::text,30) from generate_series(1,1000000) g(i);
create index idx_test on test(a,b);
vacuum analyze test;

=# explain (analyze,buffers) select a,b,c from test where a < 100000;
                                                          QUERY PLAN                                                           
-------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on test  (cost=2314.84..31673.91 rows=99925 width=190) (actual time=65.428..109.311 rows=100283 loops=1)
   Recheck Cond: (a < 100000)
   Heap Blocks: exact=27483
   Buffers: shared hit=27870
   ->  Bitmap Index Scan on idx_test  (cost=0.00..2289.86 rows=99925 width=0) (actual time=57.979..57.979 rows=100283 loops=1)
         Index Cond: (a < 100000)
         Buffers: shared hit=387
 Planning time: 0.247 ms
 Execution time: 114.687 ms
(9 rows)

=# explain (analyze,buffers) select a,b from test where a < 100000;
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 Index Only Scan using idx_test on test  (cost=0.42..3289.11 rows=99925 width=10) (actual time=0.092..42.901 rows=100283 loops=1)
   Index Cond: (a < 100000)
   Heap Fetches: 0
   Buffers: shared hit=388
 Planning time: 0.256 ms
 Execution time: 56.436 ms
(6 rows)
```

The difference in runtime isn't that great here, because it all fits in the RAM. But the first query accesses 100 times more blocks, as it has to visit the table in a random order instead of only scanning a well ordered index. On large data sets, performance can vary several orders of magnitude.


* Some data may not be inlined in the table, even if it is a row-based database. Oracle and Postgresql sometimes store data out of line, if it is too big to fit in a block. A big text field for instance, or a bytea.

```
create table test (a int, b varchar);
insert into test
-- create a big garbage column ... it has to be quite big, or, as PG will compress it, it may still fit
select (random()*1000000)::int,
           array_to_string(array ( select  
                  substr('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', 
                              trunc(random() * 62)::integer + 1, 1)
FROM   generate_series(1, 1000000)), '') from generate_series(1,1000) g(i);
Time: 1,788 ms
=# explain (analyze,buffers) select a,b||'a' from test ;
                                               QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
 Seq Scan on test  (cost=0.00..19.50 rows=1000 width=36) (actual time=1.624..396.937 rows=1000 loops=1)
   Buffers: shared hit=130383
 Planning time: 0.098 ms
 Execution time: 397.124 ms
(4 rows)

Time: 397,731 ms
=# explain (analyze,buffers) select a from test ;
                                             QUERY PLAN                                              
-----------------------------------------------------------------------------------------------------
 Seq Scan on test  (cost=0.00..17.00 rows=1000 width=4) (actual time=0.044..0.851 rows=1000 loops=1)
   Buffers: shared hit=7
 Planning time: 0.096 ms
 Execution time: 1.238 ms
(4 rows)

Time: 2,126 ms
```

I had to cheat a bit on this second one: as explain analyze doesn't return the row, PG is smart and wont access b if I don't force it to do something on b. If I did return the data to a client, PG would have accessed b, like in this example (see the difference in block hits)

* Another one that comes to my mind is ordering/hashing: memory costs are very different depending on the selected colums:

```
create table test (a int, b varchar);
insert into test select i,repeat((i::text),10) from generate_series(1,100000) g(i);
marc=# explain analyze select a,b from test order by a;
                                                    QUERY PLAN                                                     
-------------------------------------------------------------------------------------------------------------------
 Sort  (cost=10325.82..10575.82 rows=100000 width=53) (actual time=167.657..194.548 rows=100000 loops=1)
   Sort Key: a
   Sort Method: external sort  Disk: 6240kB
   ->  Seq Scan on test  (cost=0.00..2021.00 rows=100000 width=53) (actual time=0.050..29.298 rows=100000 loops=1)
 Planning time: 0.206 ms
 Execution time: 199.617 ms
(6 rows)

Time: 200,561 ms
marc=# explain analyze select a from test order by a;
                                                    QUERY PLAN                                                    
------------------------------------------------------------------------------------------------------------------
 Sort  (cost=10325.82..10575.82 rows=100000 width=4) (actual time=72.151..81.108 rows=100000 loops=1)
   Sort Key: a
   Sort Method: quicksort  Memory: 7760kB
   ->  Seq Scan on test  (cost=0.00..2021.00 rows=100000 width=4) (actual time=0.041..33.913 rows=100000 loops=1)
 Planning time: 0.136 ms
 Execution time: 84.537 ms
(6 rows)

Time: 85,161 ms
```

There i chose a work_mem (the memory used for sorts) so that the change is obvious... there is more to sort when you ask for all the columns, so here it has to sort on disk. The same applies for hashes used for aggregates or joins for instance.

**Comment by adamchainz** [comment]
Fair enough. But in my experience optimizers work very differently in production compared to test environments, as the dataset is much bigger. Any instrumentation you can get from production is tends to be worth 10x.

`django-perf-rec` is mostly intended to catch more obvious problems, like N+1 queries and unintended joins, rather than such relatively nuanced performance problems. It can be hard to figure out how many queries the Django ORM will even execute, let alone which tables they will touch :)

Still I will accept this feature when it's optional, default-off.

**Comment by zebuline** [comment]
The feature is optional, default-off (or default-on, depending on the wording :) )
https://github.com/adamchainz/django-perf-rec/pull/159/files#diff-c3a36757e150957275f1de9b38bd100cR11

**Comment by adamchainz** [comment]
Hey @zebuline , sorry this took some time to come back to. I've merged and released in 3.1.0: https://pypi.org/project/django-perf-rec/ . See #169 for some post-commit tidy up I did, instead of asking you for those changes through review. I wrote a detailed description there to walk through the changes I thought were necessary, hope it helps as educational reading. Thanks for your contribution, hope you can make more here or on other projects in the future - don't be discouraged by my slow response time here!

**Pull request merged**
