### PR TITLE
Don't replace columns in ORDER BY, GROUP BY, and HAVING clauses

### LINKED ISSUE #143: Don't replace ORDER BY elements with "..."
Ordering a query on columns or not, and the specifics of what column and in what order can be extremely relevant to understand why 2 seemingly identical queries run in either milliseconds or minutes. Given that the number of elements in the `ORDER BY` clause is generally quite limited, the interest of replacing the columns by `...` in the `ORDER BY` clause can be limited too.

I read the source of django-perf-rec and the source of sqlparse it uses, and my understanding is that this replacement is actually a side effect of sqlparse not identifying directly when a list of columns is in an `ORDER BY` or not, but I believe we could make a (probably a bit contrieved) improvement to `sql_recursively_simplify` to avoid that. Would it be accepted as a PR ? Would it need a special setting ?

I think the idea would be that whatever (non whitespace) token follows a `Keyword.ORDER` and a `Keyword.BY` would be left as-is.

### PR DESCRIPTION
**Pull request by ewjoachim**
Fixes #143

I can write more unit tests if you'd like. I've tried to not change too much the existing function and put the specific logic of detecting `order by` in a dedicated generator. Let me know if the approach works for you.

And, again, if you think this is worth having a setting, I can put one (I guess the default value would be for keeping compatibility, but it means new users will not have the columns in their `order by`).

### CODE REVIEW

**Comment by ewjoachim** [comment]
Hello, thank you a lot for your quick review !

Is it better now ?

**Comment by ewjoachim** [comment]
We'll need to sort this out too : https://github.com/YPlan/django-perf-rec/pull/145#issuecomment-404249410

**Comment by adamchainz** [comment]
Out in version 3.0.0 ! https://pypi.org/project/django-perf-rec/

**Comment by ewjoachim** [comment]
Nice ! Thanks !

**Pull request merged**
